from backend.orchestrator.conversational_flow import run_flow
from backend.state.session_manager import get_session


def handle_request(client_id, message):
    print(f"[CHAT] Incoming: {message}")

    try:
        # 🔥 Obtener sesión del cliente
        session = get_session(client_id)

        # 🔥 PASAMOS session correctamente
        response = run_flow(client_id, message, session)

        if not response:
            return "⚠️ No response generated by system"

        return str(response)

    except Exception as e:
        print(f"[ERROR] {e}")
        return "❌ Internal error processing request"
